### ISSUE TITLE
client.type? TS says 👎🏼 , Example shows 👍🏼 

### ISSUE THREAD

**Issue by mountainash** [managed-components/create-managed-component#3]
Code example in [Docs](https://managedcomponents.dev/specs/manager-events/user-events) show `if (client.type === 'browser') { ...`

But the TypeScript interface doesn't show this as a property: https://github.com/managed-components/types/blob/5d109dbffa340095a9ec0a93b35dcd9260fa2826/index.d.ts#L72

**Comment by jonnyparris** [comment]
thanks for flagging - the docs have been updated to use a more consistent example for now. Verifying device type on the client object will come later
